food/urls.py
app_name='food'
from django.urls import path
from . import views
from django.urls import include
urlpatterns=[ path('index/',views.index,name="index"),
             path('detail/<int:pk>/',views.detail,name='detail'),
             path("",views.home,name="home"),
             path('insert',views.add_item,name="insert"),
             path('update/<int:pk>',views.edit_item,name='update'),
             path('delete/<int:pk>/',views.delete_item,name='delete'),
             
             ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include("food.urls")),
    path("",include("food.urls")),
    path('register/',user_views.register,name='register'),
    path('profile',user_views.profilepage,name='profile'),
    path('passchange/',user_views.passchange,name='passchange'),
    # path("setpass/<str:email>/",user_views.setpass,name='setpass'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html',),name='logout'),
    path('updateprofile/',user_views.profileupdate,name='updateprofile'),
]
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

drinks/models.py
from django.db import models
class refre(models.Model):
    name=models.CharField(max_length=50)
    price=models.IntegerField()
    image=models.CharField(max_length=1000)


    def __str__(self):
        return self.name

food/models.py
from django.db import models

class item(models.Model):
    name=models.CharField(max_length=40)
    desc=models.CharField(max_length=30)
    price=models.IntegerField()
    image=models.CharField(max_length=600,default="https://st.depositphotos.com/1106005/3146/i/450/depositphotos_31468817-stock-photo-coming-soon-sign.jpg")

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='profilepic.jpg',upload_to='profile_pictures/')
    location=models.CharField(max_length=40)
  

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import item
class itemform(forms.ModelForm):
    # name=forms.CharField(max_length=40)
    # desc=forms.CharField(max_length=30)
    # price=forms.IntegerField()
    # image=forms.CharField(max_length=600)
    class Meta:
        model=item
        fields='__all__'

    # def save(self,**cleaned_data):
    #     name=cleaned_data.get('name')
    #     desc=cleaned_data.get('desc')
    #     price=cleaned_data.get('price')
    #     image=cleaned_data.get('image')
    #     return item.objects.create(name=name,desc=desc,price=price,image=image)




    # def update(self,instance,**cleaned_data):    
    #     instance.name=cleaned_data.get('name',instance.name)
    #     instance.desc=cleaned_data.get('desc',instance.desc)
    #     instance.price=cleaned_data.get('price',instance.price)
    #     instance.image=cleaned_data.get('image',instance.image)
    #     instance.save()
    #     return instance



    

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class RegisterForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']

class Profileform(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['image','location']        

drinks/views.py
from django.shortcuts import render

# Create your views here.

food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import item
from django.template import loader
from .forms import itemform
from django.http import Http404
from django.contrib.auth.decorators import login_required
@login_required
def index(request):
    item_list=item.objects.all()
    # return HttpResponse(item_list)
    temp=loader.get_template('food/index.html')
    context={'item_list':item_list,}
    return HttpResponse(temp.render(context,request))
@login_required
def detail(request,pk):
    obj=item.objects.get(id=pk)
    return render(request,'food/detail.html',{'obj':obj})

def home(request):
    return render(request,'food/home.html')
@login_required
def add_item(request):
    form=itemform(request.POST or None)
    if form.is_valid():
        form.save()
        # name=form.cleaned_data.get('name')
        # desc=form.cleaned_data.get('desc')
        # price=form.cleaned_data.get('price')
        # image=form.cleaned_data.get('image')
        # item.objects.create(name=name,desc=desc,price=price,image=image)


        return redirect('food:index')

    
    return render(request,'food/item_form.html',{'form':form})
@login_required
def edit_item(request,pk):
    insta=item.objects.get(id=pk)
    form=itemform(request.POST or None,instance=insta)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item_form.html',{'form':form,'insta':insta})
@login_required
def delete_item(request,pk):
    insta=item.objects.get(id=pk)
    if request.method=='POST':
        insta.delete()
        return redirect('food:index')
    return render(request,'food/item_delete.html',{'insta':insta})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.forms import PasswordResetForm,SetPasswordForm,PasswordChangeForm
from django.contrib.auth.models import User
from django.http import HttpResponse
from .forms import Profileform
from django.contrib.auth.models import User
from .models import Profile
def register(request):
    form=RegisterForm(request.POST or None)
    if form.is_valid():
        name=form.cleaned_data.get('Username')
        
        messages.success(request,f'Welcome! {name} , Your account is created.')
        form.save()
        
        return redirect('login')
    return render(request,'users/register.html',{'form':form})
@login_required
def profilepage(request):
    return render(request,'users/profile.html')

# def passreset(request):
#     form=PasswordResetForm(request.POST)
#     if form.is_valid():
#         data=form.cleaned_data.get('email')
#         obj=User.objects.get(email=data)
#         if obj.email:
#            return redirect('setpass', email=obj.email)
        
#     return render(request,'users/passwordreset.html',{'form':form}) 
@login_required   
def passchange(request):
    form=PasswordChangeForm(request.user, request.POST)
    if form.is_valid():
        form.save()
        return HttpResponse("<h3>Your password is changed successfully</h3>")
    return render(request,'users/passchange.html',{'form':form})


# def setpass(request, email):
#     if email:
#         obj=User.objects.get(email=email)
#         a=SetPasswordForm(obj, request.POST)
#         if a.is_valid():
#             a.save()
#             return HttpResponse("helooooooooooooooooo")
        
#         return render(request,'users/setpass.html',{'a':a})   
    
# @login_required  
# def profilecreate(request):      
   
#     form=Profileform(request.POST, request.FILES)
#     if form.is_valid():
#         image=form.cleaned_data.get('image')
#         location=form.cleaned_data.get('location')
#         user=request.user
#         Profile.objects.create(user=user,location=location,image=image)

#         return redirect('food:index')
    
#     return render(request,'users/profilecreate.html',{'form':form})

@login_required
def profileupdate(request):
    profile=request.user.profile
    form=Profileform(request.POST or None,request.FILES,instance=profile)
    if form.is_valid():
        form.save()
        
       

        return redirect('food:index')
    
    return render(request,'users/profilecreate.html',{'form':form,'profile':profile})

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'food/css/style.css' %}">   
    <link rel="stylesheet" href="{% static 'food/css/style2.css'%}">
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand navbar-brand-red" href="{% url 'food:index'%}">Food and Drinks</a>
        <div class="navbar">
            <a class="nav-item" href="{% url 'food:insert'%}">Add Item</a>
            {% if user.is_authenticated%}
                <a class="nav-item " href="{% url 'logout'%}">Logout</a>
                <a class="nav-item " href="{% url 'profile'%}">Profile</a>
                <a class="nav-item ">{{user.username}}</a>
                <a class="nav-item" href="{%url 'passchange'%}">Change Password</a>
            {% else %}
                <a class="nav-item" href="{% url 'login' %}">Login</a>
                <a class="nav-item" href="{% url 'register' %}">Register</a>
            {% endif %}    
        </div>
        
      
        
    </nav>
    {% if messages %}
        {% for message in messages %}
             <div class="alert-alert-{{messages.tags}}">{{message}}</div>
        {% endfor %}
    {% endif %}         
    {% block body %}
    {% endblock %}
    
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}
<br>
<br>
    <div class="row">
        <div class="col-md-4 offset-md-2">
            <img class="card" src="{{obj.image}}" height="200px" width="250px">
        </div>
        <div class="col-md-4">
            <h3>{{obj.name}}</h3>
            <h4>{{obj.desc}}</h4>
            <h5>${{obj.price}}</h5>
        </div>
        <div class="col-md-2">
            <a class="btn btn-success" href="{%url 'food:update' obj.id%}">Update</a>
            <br>
            <br>
            <br>
            <a class="btn btn-success" href="{%url 'food:delete' obj.id%}"> Delete</a>

        </div>
       
    </div>
{% endblock %}

food/templates/food/home.html
{% extends 'food/base.html' %}
{% block body %}
<h1> Welcome!</h1>
<h3>Visit the section you want to explore</h3>
<div class="row">
    <div class="col-md-4 offset-md-2">
        <a href="{% url 'food:index'%}"><img class="card" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSR1h2Isr2mzM8CqP3oPt7FMCqMY-Cq1CKK8w&s" height="300px" width="300px" </a>
    </div>
    <div class="col-md-3 offset-md-3">
        <a href="{% url 'food:index' %}"><h4>Food Items</h4></a>

    </div>
    
</div>
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
{% load static %} 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

</head>
<body>
    {% block body %}
    {% for item in item_list %}
        <br>

        <div class="row">
            <div class="col-md-4 offset-md-2">
                <img class="card" src="{{item.image}}" height="200px" width="200px">
            </div>

           <div class="col-md-3">
                <h4>{{item.name}}</h4> 
                <h5>{{item.desc}}</h5>
                <h6>${{item.price}}</h6>

            </div>
            <div class="col-md-3">
               <a class="btn btn-success" href="{%url 'food:detail' item.id %}">Detail</a>
            </div>
           </div> 
    {%endfor%}    
    {% endblock %} 

    
</body>
</html>

food/templates/food/item_delete.html
<form method="POST">
    {%csrf_token%}
    <h2>Are you sure you want to delete the item {{insta.name}}</h2>
    <button type="submit">Yes,Sure!</button>
</form>

food/templates/food/item_form.html
{% extends 'food/base.html'%}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Save</button>
</form>
{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}
{%block body%}
<br>

<form method="POST">
    {%csrf_token%}
    {{form}}
    <button type="submit" >Login</button>
</form>
<br>
<br>
<h4>New User</h4>
<a class="btn btn-sucess" href="{% url 'register' %}">Register Here</a>
{% endblock %}

users/templates/users/logout.html
{% extends 'food/base.html' %}
{% block body%}
<form method="POST">
    <h2>You have been successfully Logged Out</h2>
</form>
{% endblock%}

users/templates/users/passchange.html
<form method="POST">
    {%csrf_token%}
    {{form}}
    <button type="submit" class="btn btn-success">Change Password</button>
</form>

users/templates/users/profile.html
{%extends 'food/base.html'%}
{%block body%}
Name : <h2>{{user.username}}</h2>
Profile Picture :<img src="{{user.profile.image.url}}" height="200px" width="200px" >
<br>
<br>
Location :<h4>{{user.profile.location}}</h4>

<a class="btn btn-success" href="{% url 'updateprofile' %}">Update Profile</a>


{%endblock%}

users/templates/users/profilecreate.html
<form method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    {{form}}
    <button type="submit">Register</button>
</form>

users/templates/users/register.html
<form method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    {{form}}
    <button type="submit">Register</button>
</form>